# Generated by Django 4.2.7 on 2023-12-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_library'),
    ]

    operations = [
        migrations.DeleteModel(
            name='library',
        ),
    ]
