# Generated by Django 4.2.7 on 2023-12-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('img', models.ImageField(upload_to='library')),
                ('file', models.FileField(upload_to='library')),
                ('desc', models.TextField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
